name: build_runner
version: 2.4.7-dev
description: A build system for Dart code generation and modular compilation.
repository: https://github.com/dart-lang/build/tree/master/build_runner

environment:
  sdk: ^3.0.6

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: '>=4.4.0 <7.0.0'
  args: ^2.0.0
  async: ^3.0.5
  build: ">=2.1.0 <2.5.0"
  build_config: ">=1.1.0 <1.2.0"
  build_daemon: ^4.0.0
  build_resolvers: ^2.0.0
  build_runner_core: ^7.2.0
  code_builder: ^4.2.0
  collection: ^1.15.0
  crypto: ^3.0.0
  dart_style: ^2.3.2
  frontend_server_client: ^3.0.0
  glob: ^2.1.2
  graphs: ^2.2.0
  http_multi_server: ^3.0.0
  io: ^1.0.0
  js: ^0.6.3
  logging: ^1.0.0
  meta: ^1.9.1
  mime: ^1.0.4
  package_config: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.1
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  stack_trace: ^1.11.1
  stream_transform: ^2.0.0
  timing: ^1.0.0
  watcher: ^1.1.0
  web_socket_channel: ^2.0.0
  yaml: ^3.1.2

dev_dependencies:
  _test_common:
    path: ../_test_common
  build_test: ^2.0.0
  build_web_compilers: ^4.0.0
  dart_flutter_team_lints: ^1.0.0
  stream_channel: ^2.0.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0
